"""Demo catalogue: (title, authors, year, subjects, description, material, audience, language, dewey, isbn)."""

BOOKS = [
    ("Pride and Prejudice", ["Austen, Jane"], 1813, ["Courtship -- Fiction", "Social classes -- England -- Fiction", "Romance"],
     "Elizabeth Bennet spars with the proud Mr Darcy in a witty comedy of manners about marriage, money and first impressions in Regency England.", "book", "adult", "en", "823.7", "9780141439518"),
    ("Moby-Dick", ["Melville, Herman"], 1851, ["Whaling -- Fiction", "Sea stories", "Obsession -- Fiction"],
     "Ishmael ships aboard the whaler Pequod, whose captain Ahab is consumed by his hunt for the white whale that took his leg.", "book", "adult", "en", "813.3", "9780142437247"),
    ("Frankenstein", ["Shelley, Mary Wollstonecraft"], 1818, ["Science fiction", "Gothic fiction", "Scientists -- Fiction", "Monsters -- Fiction"],
     "A young scientist creates life from dead matter and is pursued by the consequences of abandoning his creature. A founding work of science fiction and gothic horror.", "book", "adult", "en", "823.7", "9780141439471"),
    ("Dracula", ["Stoker, Bram"], 1897, ["Vampires -- Fiction", "Horror tales", "Gothic fiction"],
     "Told through letters and diaries, a band of friends confronts the ancient Transylvanian count who has come to London.", "book", "adult", "en", "823.8", "9780141439846"),
    ("The Adventures of Sherlock Holmes", ["Doyle, Arthur Conan"], 1892, ["Detective and mystery stories", "Holmes, Sherlock (Fictitious character)", "Crime"],
     "Twelve cases for the consulting detective of Baker Street and his loyal friend Dr Watson, from a royal scandal to a speckled band.", "book", "adult", "en", "823.8", "9780140439076"),
    ("The Hound of the Baskervilles", ["Doyle, Arthur Conan"], 1902, ["Detective and mystery stories", "Holmes, Sherlock (Fictitious character)", "Moors (Wetlands) -- Fiction"],
     "Holmes and Watson investigate a family curse and a spectral hound haunting the misty moors of Devon.", "book", "young_adult", "en", "823.8", "9780140437867"),
    ("Murder on the Orient Express", ["Christie, Agatha"], 1934, ["Detective and mystery stories", "Poirot, Hercule (Fictitious character)", "Railroad travel -- Fiction"],
     "Snowbound on a luxury train, Hercule Poirot must find which of the passengers stabbed a wealthy American in his compartment.", "book", "adult", "en", "823.912", "9780062693662"),
    ("And Then There Were None", ["Christie, Agatha"], 1939, ["Detective and mystery stories", "Islands -- Fiction", "Suspense fiction"],
     "Ten strangers lured to an island are killed one by one, following the lines of a sinister nursery rhyme.", "book", "adult", "en", "823.912", "9780062073488"),
    ("The Time Machine", ["Wells, H. G."], 1895, ["Time travel -- Fiction", "Science fiction", "Future -- Fiction"],
     "A Victorian inventor travels to the year 802,701 and finds humanity split into the gentle Eloi and the subterranean Morlocks.", "book", "adult", "en", "823.8", "9780451530707"),
    ("The War of the Worlds", ["Wells, H. G."], 1898, ["Science fiction", "Martians -- Fiction", "Invasion -- Fiction", "Space"],
     "Martian cylinders land in Surrey and tripod fighting machines lay waste to England in the classic alien-invasion story.", "book", "adult", "en", "823.8", "9780141441030"),
    ("Twenty Thousand Leagues Under the Seas", ["Verne, Jules"], 1870, ["Submarines -- Fiction", "Sea stories", "Adventure stories", "Science fiction"],
     "Professor Aronnax is taken prisoner aboard Captain Nemo's submarine Nautilus for a voyage through the wonders of the ocean.", "book", "young_adult", "en", "843.8", "9780140394474"),
    ("Around the World in Eighty Days", ["Verne, Jules"], 1872, ["Voyages around the world -- Fiction", "Adventure stories", "Wagers -- Fiction"],
     "Phileas Fogg bets his fortune that he can circle the globe in eighty days, with his valet Passepartout and a detective in pursuit.", "book", "young_adult", "en", "843.8", "9780140449068"),
    ("Treasure Island", ["Stevenson, Robert Louis"], 1883, ["Pirates -- Fiction", "Buried treasure -- Fiction", "Adventure stories", "Sea stories"],
     "Young Jim Hawkins sails in search of Captain Flint's treasure and tangles with the charming, treacherous Long John Silver.", "book", "children", "en", "823.8", "9780141321004"),
    ("Strange Case of Dr Jekyll and Mr Hyde", ["Stevenson, Robert Louis"], 1886, ["Psychological fiction", "Horror tales", "Good and evil -- Fiction"],
     "A London lawyer investigates the link between a respected physician and a brutal man who seems to come and go from his house.", "book", "adult", "en", "823.8", "9780141389509"),
    ("Alice's Adventures in Wonderland", ["Carroll, Lewis"], 1865, ["Fantasy fiction", "Children's stories", "Imaginary places -- Fiction"],
     "Alice follows a white rabbit down a hole into a nonsensical world of talking animals, mad tea parties and a furious queen.", "book", "children", "en", "823.8", "9780141321073"),
    ("The Wonderful Wizard of Oz", ["Baum, L. Frank"], 1900, ["Fantasy fiction", "Children's stories", "Magic -- Fiction", "Oz (Imaginary place)"],
     "A cyclone carries Dorothy to the land of Oz, where she journeys along the yellow brick road with a scarecrow, a tin man and a lion.", "book", "children", "en", "813.4", "9780140621679"),
    ("The Jungle Book", ["Kipling, Rudyard"], 1894, ["Jungles -- India -- Fiction", "Animals -- Fiction", "Children's stories"],
     "Mowgli, a boy raised by wolves in the Indian jungle, learns its law from Baloo the bear and Bagheera the panther while Shere Khan waits.", "book", "children", "en", "823.8", "9780141325293"),
    ("Kim", ["Kipling, Rudyard"], 1901, ["India -- Fiction", "Spies -- Fiction", "Coming of age -- Fiction"],
     "An orphan on the streets of Lahore becomes the disciple of a Tibetan lama and an apprentice in the Great Game of espionage.", "book", "adult", "en", "823.8", "9780141441979"),
    ("Peter Pan", ["Barrie, J. M."], 1911, ["Fantasy fiction", "Children's stories", "Fairies -- Fiction", "Pirates -- Fiction"],
     "Wendy and her brothers fly to Neverland with the boy who will not grow up, and face Captain Hook.", "book", "children", "en", "823.912", "9780141322575"),
    ("Little Women", ["Alcott, Louisa May"], 1868, ["Sisters -- Fiction", "Families -- New England -- Fiction", "Coming of age -- Fiction"],
     "The four March sisters grow up during the American Civil War, each pursuing her own dreams of art, love and independence.", "book", "young_adult", "en", "813.4", "9780147514011"),
    ("Anne of Green Gables", ["Montgomery, L. M."], 1908, ["Orphans -- Fiction", "Prince Edward Island -- Fiction", "Coming of age -- Fiction"],
     "A talkative, imaginative orphan is sent by mistake to an elderly brother and sister who wanted a boy for their farm.", "book", "children", "en", "813.52", "9780141321592"),
    ("The Secret Garden", ["Burnett, Frances Hodgson"], 1911, ["Gardens -- Fiction", "Orphans -- Fiction", "Children's stories", "Healing -- Fiction"],
     "Lonely Mary Lennox discovers a locked garden on a Yorkshire estate and, in bringing it back to life, transforms herself and her cousin.", "book", "children", "en", "823.912", "9780141321066"),
    ("Great Expectations", ["Dickens, Charles"], 1861, ["Orphans -- Fiction", "Social classes -- England -- Fiction", "Coming of age -- Fiction"],
     "The orphan Pip receives a fortune from a mysterious benefactor and must learn what makes a true gentleman.", "book", "adult", "en", "823.8", "9780141439563"),
    ("A Tale of Two Cities", ["Dickens, Charles"], 1859, ["France -- History -- Revolution, 1789-1799 -- Fiction", "Historical fiction", "London -- Fiction"],
     "Lives in London and Paris become entangled in the turmoil and terror of the French Revolution.", "book", "adult", "en", "823.8", "9780141439600"),
    ("Oliver Twist", ["Dickens, Charles"], 1838, ["Orphans -- Fiction", "Criminals -- London -- Fiction", "Poverty -- Fiction"],
     "A workhouse orphan falls among a gang of London pickpockets led by the sinister Fagin.", "book", "adult", "en", "823.8", "9780141439747"),
    ("Jane Eyre", ["Brontë, Charlotte"], 1847, ["Governesses -- Fiction", "Love stories", "Gothic fiction"],
     "A plain, principled governess falls in love with her brooding employer, Mr Rochester, whose house hides a terrible secret.", "book", "adult", "en", "823.8", "9780141441146"),
    ("Wuthering Heights", ["Brontë, Emily"], 1847, ["Revenge -- Fiction", "Love stories", "Yorkshire (England) -- Fiction", "Gothic fiction"],
     "The passionate, destructive bond between Heathcliff and Catherine Earnshaw echoes across two generations on the Yorkshire moors.", "book", "adult", "en", "823.8", "9780141439556"),
    ("Emma", ["Austen, Jane"], 1815, ["Matchmaking -- Fiction", "Romance", "Comedy of manners"],
     "Handsome, clever and rich, Emma Woodhouse meddles in her neighbours' love lives with comic and humbling results.", "book", "adult", "en", "823.7", "9780141439587"),
    ("Sense and Sensibility", ["Austen, Jane"], 1811, ["Sisters -- Fiction", "Romance", "Inheritance and succession -- Fiction"],
     "Sisters Elinor and Marianne Dashwood, one prudent and one passionate, face reduced circumstances and disappointed love.", "book", "adult", "en", "823.7", "9780141439662"),
    ("The Picture of Dorian Gray", ["Wilde, Oscar"], 1890, ["Portraits -- Fiction", "Beauty, Personal -- Fiction", "Gothic fiction"],
     "A beautiful young man stays unchanged while his portrait records every sin of his secret, decadent life.", "book", "adult", "en", "823.8", "9780141439570"),
    ("The Importance of Being Earnest", ["Wilde, Oscar"], 1895, ["Comedy", "Drama", "Mistaken identity -- Drama"],
     "Two young gentlemen invent alter egos to escape their obligations in Wilde's sparkling comedy of manners.", "book", "adult", "en", "822.8", "9780486264783"),
    ("Hamlet", ["Shakespeare, William"], 1603, ["Drama", "Tragedies", "Revenge -- Drama", "Denmark -- Drama"],
     "The Prince of Denmark, visited by his father's ghost, wrestles with revenge, madness and mortality.", "book", "adult", "en", "822.33", "9780743477123"),
    ("Macbeth", ["Shakespeare, William"], 1623, ["Drama", "Tragedies", "Ambition -- Drama", "Scotland -- Drama"],
     "Spurred by witches' prophecy and his wife's ambition, a Scottish general murders his way to the throne.", "book", "adult", "en", "822.33", "9780743477109"),
    ("Romeo and Juliet", ["Shakespeare, William"], 1597, ["Drama", "Tragedies", "Love -- Drama", "Verona (Italy) -- Drama"],
     "Two young lovers from feuding families in Verona marry in secret, with tragic consequences.", "book", "young_adult", "en", "822.33", "9780743477116"),
    ("The Odyssey", ["Homer", "Fagles, Robert"], -700, ["Epic poetry, Greek", "Odysseus (Greek mythology) -- Poetry", "Voyages and travels -- Poetry"],
     "Odysseus struggles for ten years to return home from Troy, past monsters, gods and temptations.", "book", "adult", "en", "883.01", "9780140268867"),
    ("The Iliad", ["Homer", "Fagles, Robert"], -750, ["Epic poetry, Greek", "Trojan War -- Poetry", "Achilles (Greek mythology) -- Poetry"],
     "The rage of Achilles during the final year of the Trojan War, and its cost to Greeks and Trojans alike.", "book", "adult", "en", "883.01", "9780140275360"),
    ("Meditations", ["Marcus Aurelius"], 180, ["Stoics", "Ethics", "Philosophy, Ancient"],
     "Private notes of a Roman emperor on duty, mortality, self-discipline and the Stoic way of meeting adversity.", "book", "adult", "en", "188", "9780140449334"),
    ("The Republic", ["Plato"], -375, ["Political science -- Philosophy", "Justice -- Philosophy", "Philosophy, Ancient", "Utopias"],
     "Socrates and his companions ask what justice is and sketch an ideal city ruled by philosopher-kings.", "book", "adult", "en", "321.07", "9780140455113"),
    ("The Art of War", ["Sunzi"], -500, ["Military art and science", "Strategy", "Philosophy, Chinese"],
     "Ancient Chinese treatise on strategy, deception and winning without fighting, still read by generals and executives.", "book", "adult", "en", "355.02", "9781590302255"),
    ("On the Origin of Species", ["Darwin, Charles"], 1859, ["Evolution (Biology)", "Natural selection", "Species"],
     "Darwin's landmark argument that species evolve over generations through natural selection.", "book", "adult", "en", "576.82", "9780451529060"),
    ("A Brief History of Time", ["Hawking, Stephen"], 1988, ["Cosmology", "Astrophysics", "Black holes (Astronomy)", "Space and time"],
     "A tour of the universe from the big bang to black holes, explaining modern cosmology for the general reader.", "book", "adult", "en", "523.1", "9780553380163"),
    ("Cosmos", ["Sagan, Carl"], 1980, ["Astronomy", "Cosmology", "Science -- History", "Space"],
     "A lyrical journey through fifteen billion years of cosmic evolution and the human quest to understand the stars.", "book", "adult", "en", "520", "9780345539434"),
    ("Pale Blue Dot", ["Sagan, Carl"], 1994, ["Outer space -- Exploration", "Astronomy", "Planets"],
     "Sagan reflects on humanity's place in the universe and the future of space exploration.", "book", "adult", "en", "919.904", "9780345376596"),
    ("The Selfish Gene", ["Dawkins, Richard"], 1976, ["Genetics", "Evolution (Biology)", "Animal behavior"],
     "Dawkins argues that evolution is best understood from the gene's point of view, introducing the idea of the meme.", "book", "adult", "en", "591.5", "9780198788607"),
    ("Silent Spring", ["Carson, Rachel"], 1962, ["Pesticides -- Environmental aspects", "Ecology", "Nature conservation", "Environment"],
     "The book that launched the environmental movement by documenting the effects of pesticides on birds and ecosystems.", "book", "adult", "en", "363.7384", "9780618249060"),
    ("The Sixth Extinction", ["Kolbert, Elizabeth"], 2014, ["Extinction (Biology)", "Climate change", "Ecology", "Nature -- Effect of human beings on"],
     "A reporter travels the world to show how human activity is driving a mass extinction of species.", "book", "adult", "en", "576.84", "9781250062185"),
    ("Sapiens: A Brief History of Humankind", ["Harari, Yuval Noah"], 2011, ["Human beings -- History", "Civilization -- History", "Human evolution"],
     "A sweeping history of our species, from foragers to farmers to the scientific and capitalist revolutions.", "book", "adult", "en", "909", "9780062316097"),
    ("Guns, Germs, and Steel", ["Diamond, Jared"], 1997, ["Civilization -- History", "Social evolution", "Geography -- History"],
     "Why did some societies conquer others? Diamond points to geography, crops, animals and germs.", "book", "adult", "en", "303.4", "9780393354324"),
    ("The Discovery of India", ["Nehru, Jawaharlal"], 1946, ["India -- History", "India -- Civilization", "Nationalism -- India"],
     "Written in prison, Nehru's reflection on India's history, philosophy and culture from ancient times to the independence struggle.", "book", "adult", "en", "954", "9780143031031"),
    ("The Story of My Experiments with Truth", ["Gandhi, Mahatma"], 1927, ["Gandhi, Mahatma, 1869-1948", "Autobiography", "Nonviolence", "India -- Politics and government"],
     "Gandhi's autobiography, tracing his moral and political development from childhood to the 1920s.", "book", "adult", "en", "954.035092", "9780807059098"),
    ("Wings of Fire", ["Kalam, A. P. J. Abdul", "Tiwari, Arun"], 1999, ["Kalam, A. P. J. Abdul, 1931-2015", "Autobiography", "Rocketry -- India", "Space"],
     "The autobiography of India's 'missile man', from a boyhood in Rameswaram to leading the country's space and defence programmes.", "book", "young_adult", "en", "623.4519092", "9788173711466"),
    ("Malgudi Days", ["Narayan, R. K."], 1943, ["Short stories", "India -- Social life and customs -- Fiction", "Small cities -- Fiction"],
     "Gently comic stories of the people of Malgudi, Narayan's fictional South Indian town.", "book", "adult", "en", "823.912", "9780143039655"),
    ("Swami and Friends", ["Narayan, R. K."], 1935, ["Boys -- India -- Fiction", "Friendship -- Fiction", "School stories"],
     "Ten-year-old Swaminathan's adventures and misadventures with school, cricket and friends in Malgudi.", "book", "children", "en", "823.912", "9780226568317"),
    ("Godaan", ["Premchand, Munshi"], 1936, ["Peasants -- India -- Fiction", "Poverty -- Fiction", "Hindi fiction"],
     "Hori, a poor farmer, dreams of owning a cow, in Premchand's classic portrait of rural exploitation in colonial India.", "book", "adult", "hi", "891.433", "9788171828807"),
    ("Gitanjali", ["Tagore, Rabindranath"], 1910, ["Bengali poetry", "Devotional poetry", "Poetry"],
     "Song offerings of devotion and longing that won Tagore the Nobel Prize in Literature.", "book", "adult", "bn", "891.441", "9788171670918"),
    ("The God of Small Things", ["Roy, Arundhati"], 1997, ["Twins -- Fiction", "Kerala (India) -- Fiction", "Families -- Fiction", "Caste -- Fiction"],
     "Twins Estha and Rahel piece together the events of one devastating day in 1969 Kerala.", "book", "adult", "en", "823.914", "9780812979657"),
    ("Midnight's Children", ["Rushdie, Salman"], 1981, ["India -- History -- 20th century -- Fiction", "Magic realism (Literature)", "Telepathy -- Fiction"],
     "Born at the stroke of India's independence, Saleem Sinai discovers he is telepathically linked to the nation's other midnight children.", "book", "adult", "en", "823.914", "9780812976533"),
    ("A Suitable Boy", ["Seth, Vikram"], 1993, ["India -- Social life and customs -- Fiction", "Marriage -- Fiction", "Families -- Fiction"],
     "In newly independent India, Mrs Rupa Mehra searches for a suitable husband for her daughter Lata.", "book", "adult", "en", "823.914", "9780060786526"),
    ("The White Tiger", ["Adiga, Aravind"], 2008, ["Social classes -- India -- Fiction", "Chauffeurs -- Fiction", "Satire"],
     "A darkly funny confession by a village boy turned Delhi chauffeur who murders his way to entrepreneurial success.", "book", "adult", "en", "823.92", "9781416562603"),
    ("Train to Pakistan", ["Singh, Khushwant"], 1956, ["India -- History -- Partition, 1947 -- Fiction", "Villages -- Punjab -- Fiction", "Historical fiction"],
     "A Punjabi border village is engulfed by the violence of Partition in the summer of 1947.", "book", "adult", "en", "823.914", "9780802130228"),
    ("Nineteen Eighty-Four", ["Orwell, George"], 1949, ["Dystopias", "Totalitarianism -- Fiction", "Science fiction", "Future -- Fiction"],
     "Winston Smith rebels against Big Brother's all-seeing Party in a future of perpetual war and surveillance.", "book", "adult", "en", "823.912", "9780451524935"),
    ("Animal Farm", ["Orwell, George"], 1945, ["Allegories", "Satire", "Totalitarianism -- Fiction", "Animals -- Fiction"],
     "The animals of Manor Farm overthrow their human master, only to see their revolution betrayed by the pigs.", "book", "young_adult", "en", "823.912", "9780451526342"),
    ("Brave New World", ["Huxley, Aldous"], 1932, ["Dystopias", "Science fiction", "Genetic engineering -- Fiction", "Future -- Fiction"],
     "In a World State of engineered happiness and caste, one man raised outside it questions the price of stability.", "book", "adult", "en", "823.912", "9780060850524"),
    ("Fahrenheit 451", ["Bradbury, Ray"], 1953, ["Dystopias", "Censorship -- Fiction", "Books and reading -- Fiction", "Science fiction"],
     "Fireman Guy Montag burns books for a living until a curious neighbour makes him question everything.", "book", "young_adult", "en", "813.54", "9781451673319"),
    ("Dune", ["Herbert, Frank"], 1965, ["Science fiction", "Desert planets -- Fiction", "Interplanetary voyages -- Fiction", "Space"],
     "On the desert planet Arrakis, young Paul Atreides becomes the centre of a war for the most valuable substance in the universe.", "book", "adult", "en", "813.54", "9780441172719"),
    ("Foundation", ["Asimov, Isaac"], 1951, ["Science fiction", "Galactic empires -- Fiction", "Space", "Future -- Fiction"],
     "Mathematician Hari Seldon foresees the fall of the Galactic Empire and plans to shorten the dark age that will follow.", "book", "adult", "en", "813.54", "9780553293357"),
    ("I, Robot", ["Asimov, Isaac"], 1950, ["Robots -- Fiction", "Artificial intelligence -- Fiction", "Science fiction", "Short stories"],
     "Linked stories exploring the Three Laws of Robotics and the strange ways intelligent machines can follow them.", "book", "young_adult", "en", "813.54", "9780553382563"),
    ("The Left Hand of Darkness", ["Le Guin, Ursula K."], 1969, ["Science fiction", "Gender identity -- Fiction", "Space"],
     "An envoy to the ice planet Gethen, whose people have no fixed sex, must navigate its politics to bring it into an interstellar union.", "book", "adult", "en", "813.54", "9780441478125"),
    ("A Wizard of Earthsea", ["Le Guin, Ursula K."], 1968, ["Fantasy fiction", "Wizards -- Fiction", "Magic -- Fiction", "Coming of age -- Fiction"],
     "Young Ged's pride unleashes a shadow on the world, and he must hunt it across the islands of Earthsea.", "book", "young_adult", "en", "813.54", "9780547773742"),
    ("The Hobbit", ["Tolkien, J. R. R."], 1937, ["Fantasy fiction", "Middle Earth (Imaginary place) -- Fiction", "Dragons -- Fiction", "Quests (Expeditions) -- Fiction"],
     "Bilbo Baggins is swept out of his comfortable hole on a quest with thirteen dwarves to reclaim treasure from the dragon Smaug.", "book", "young_adult", "en", "823.912", "9780547928227"),
    ("The Fellowship of the Ring", ["Tolkien, J. R. R."], 1954, ["Fantasy fiction", "Middle Earth (Imaginary place) -- Fiction", "Quests (Expeditions) -- Fiction", "Magic -- Fiction"],
     "Frodo inherits a ring of terrible power and sets out with eight companions to destroy it.", "book", "adult", "en", "823.912", "9780547928210"),
    ("Harry Potter and the Philosopher's Stone", ["Rowling, J. K."], 1997, ["Fantasy fiction", "Wizards -- Fiction", "Magic -- Fiction", "Schools -- Fiction"],
     "On his eleventh birthday an orphan learns he is a wizard and begins his first year at Hogwarts School of Witchcraft and Wizardry.", "book", "children", "en", "823.914", "9780747532699"),
    ("Charlotte's Web", ["White, E. B."], 1952, ["Pigs -- Fiction", "Spiders -- Fiction", "Friendship -- Fiction", "Children's stories"],
     "A clever spider named Charlotte saves her friend Wilbur the pig by spinning words into her web.", "book", "children", "en", "813.52", "9780064400558"),
    ("Matilda", ["Dahl, Roald"], 1988, ["Gifted children -- Fiction", "Schools -- Fiction", "Humorous stories", "Children's stories"],
     "A brilliant little girl with dreadful parents and a monstrous headmistress discovers she has an extraordinary power.", "book", "children", "en", "823.914", "9780142410370"),
    ("Charlie and the Chocolate Factory", ["Dahl, Roald"], 1964, ["Chocolate -- Fiction", "Humorous stories", "Children's stories"],
     "Five lucky children win a tour of Willy Wonka's marvellous and mysterious chocolate factory.", "book", "children", "en", "823.914", "9780142410318"),
    ("The Little Prince", ["Saint-Exupéry, Antoine de"], 1943, ["Fables", "Princes -- Fiction", "Children's stories", "Space"],
     "A pilot stranded in the desert meets a small prince from another planet who teaches him what is essential.", "book", "children", "en", "843.912", "9780156012195"),
    ("Le Petit Prince", ["Saint-Exupéry, Antoine de"], 1943, ["Fables", "Contes", "Littérature jeunesse"],
     "Un aviateur en panne dans le désert rencontre un petit prince venu d'une autre planète.", "book", "children", "fr", "843.912", "9782070612758"),
    ("Don Quixote", ["Cervantes Saavedra, Miguel de"], 1605, ["Knights and knighthood -- Fiction", "Satire", "Spain -- Fiction", "Humor"],
     "An elderly gentleman, maddened by chivalric romances, sets out as a knight-errant with his squire Sancho Panza.", "book", "adult", "en", "863.3", "9780060934347"),
    ("Cien años de soledad", ["García Márquez, Gabriel"], 1967, ["Realismo mágico", "Familias -- Ficción", "Colombia -- Ficción"],
     "La historia de siete generaciones de la familia Buendía en el pueblo mítico de Macondo.", "book", "adult", "es", "863.64", "9780307474728"),
    ("Crime and Punishment", ["Dostoyevsky, Fyodor"], 1866, ["Murder -- Fiction", "Psychological fiction", "Saint Petersburg (Russia) -- Fiction", "Crime"],
     "A destitute student murders a pawnbroker to prove a theory and is consumed by guilt and a patient detective.", "book", "adult", "en", "891.733", "9780143058144"),
    ("War and Peace", ["Tolstoy, Leo"], 1869, ["Napoleonic Wars, 1800-1815 -- Fiction", "Russia -- History -- Fiction", "Historical fiction", "War"],
     "Russian aristocratic families live, love and die through Napoleon's invasion of 1812.", "book", "adult", "en", "891.733", "9781400079988"),
    ("Anna Karenina", ["Tolstoy, Leo"], 1878, ["Adultery -- Fiction", "Russia -- Social life and customs -- Fiction", "Love stories"],
     "A married aristocrat's passionate affair with a cavalry officer sets her against the society that made her.", "book", "adult", "en", "891.733", "9780143035008"),
    ("The Metamorphosis", ["Kafka, Franz"], 1915, ["Alienation (Social psychology) -- Fiction", "Families -- Fiction", "Fantasy fiction"],
     "Gregor Samsa wakes to find himself transformed into a monstrous insect, and his family must cope.", "book", "adult", "en", "833.912", "9780553213690"),
    ("The Great Gatsby", ["Fitzgerald, F. Scott"], 1925, ["Wealth -- Fiction", "Long Island (N.Y.) -- Fiction", "Love stories", "American Dream"],
     "Nick Carraway watches his mysterious millionaire neighbour pursue a lost love across the glittering summer of 1922.", "book", "adult", "en", "813.52", "9780743273565"),
    ("To Kill a Mockingbird", ["Lee, Harper"], 1960, ["Racism -- Fiction", "Trials (Rape) -- Fiction", "Coming of age -- Fiction", "Alabama -- Fiction"],
     "Scout Finch's father defends a Black man falsely accused of rape in a small Alabama town in the 1930s.", "book", "young_adult", "en", "813.54", "9780061120084"),
    ("The Catcher in the Rye", ["Salinger, J. D."], 1951, ["Teenage boys -- Fiction", "Alienation (Social psychology) -- Fiction", "Coming of age -- Fiction"],
     "Expelled from prep school, Holden Caulfield wanders New York City for three days, raging at the phoniness of adults.", "book", "young_adult", "en", "813.54", "9780316769488"),
    ("Of Mice and Men", ["Steinbeck, John"], 1937, ["Migrant agricultural laborers -- Fiction", "Friendship -- Fiction", "California -- Fiction"],
     "Two drifters, George and the gentle giant Lennie, dream of a farm of their own during the Great Depression.", "book", "young_adult", "en", "813.52", "9780140177398"),
    ("The Old Man and the Sea", ["Hemingway, Ernest"], 1952, ["Fishers -- Fiction", "Sea stories", "Cuba -- Fiction", "Courage -- Fiction"],
     "An aging Cuban fisherman battles a giant marlin far out in the Gulf Stream.", "book", "adult", "en", "813.52", "9780684801223"),
    ("Things Fall Apart", ["Achebe, Chinua"], 1958, ["Igbo (African people) -- Fiction", "Nigeria -- History -- Fiction", "Colonization -- Fiction"],
     "Okonkwo, a proud Igbo leader, watches his world unravel with the arrival of British missionaries and colonial rule.", "book", "adult", "en", "823.914", "9780385474542"),
    ("Beloved", ["Morrison, Toni"], 1987, ["Slavery -- Fiction", "African American women -- Fiction", "Ghost stories", "Historical fiction"],
     "A woman who escaped slavery is haunted, literally and otherwise, by the daughter she lost.", "book", "adult", "en", "813.54", "9781400033416"),
    ("The Handmaid's Tale", ["Atwood, Margaret"], 1985, ["Dystopias", "Women -- Fiction", "Totalitarianism -- Fiction", "Future -- Fiction"],
     "In the theocratic Republic of Gilead, Offred is forced to bear children for the ruling class.", "book", "adult", "en", "813.54", "9780385490818"),
    ("Clean Code", ["Martin, Robert C."], 2008, ["Computer software -- Quality control", "Software engineering", "Computer programming"],
     "Principles, patterns and practices for writing readable, maintainable software, illustrated with Java case studies.", "book", "adult", "en", "005.1", "9780132350884"),
    ("The Pragmatic Programmer", ["Hunt, Andrew", "Thomas, David"], 1999, ["Computer programming", "Software engineering", "Career development"],
     "Practical advice on craftsmanship, tooling and career for programmers who care about their work.", "book", "adult", "en", "005.1", "9780135957059"),
    ("Fluent Python", ["Ramalho, Luciano"], 2022, ["Python (Computer program language)", "Computer programming", "Object-oriented programming"],
     "A deep guide to idiomatic Python 3: data model, functions, classes, concurrency and metaprogramming.", "book", "adult", "en", "005.133", "9781492056355"),
    ("Introduction to Algorithms", ["Cormen, Thomas H.", "Leiserson, Charles E.", "Rivest, Ronald L.", "Stein, Clifford"], 2009,
     ["Computer algorithms", "Computer programming", "Data structures (Computer science)"],
     "The standard comprehensive textbook on algorithms, covering sorting, graphs, dynamic programming and complexity.", "book", "adult", "en", "005.1", "9780262033848"),
    ("Artificial Intelligence: A Modern Approach", ["Russell, Stuart", "Norvig, Peter"], 2020, ["Artificial intelligence", "Machine learning", "Intelligent agents (Computer software)"],
     "The leading textbook on artificial intelligence, from search and logic to probabilistic reasoning, learning and robotics.", "book", "adult", "en", "006.3", "9780134610993"),
    ("Deep Learning", ["Goodfellow, Ian", "Bengio, Yoshua", "Courville, Aaron"], 2016, ["Machine learning", "Neural networks (Computer science)", "Artificial intelligence"],
     "A comprehensive text on deep neural networks, their mathematical foundations and practical methods.", "book", "adult", "en", "006.31", "9780262035613"),
    ("Life 3.0", ["Tegmark, Max"], 2017, ["Artificial intelligence -- Social aspects", "Technology -- Forecasting", "Future"],
     "A physicist explores how artificial intelligence could reshape work, war, justice and the future of life itself.", "book", "adult", "en", "006.301", "9781101970317"),
    ("Thinking, Fast and Slow", ["Kahneman, Daniel"], 2011, ["Thought and thinking", "Decision making", "Psychology", "Cognition"],
     "A Nobel laureate explains the two systems that drive how we think, and the biases that lead us astray.", "book", "adult", "en", "153.42", "9780374533557"),
    ("Man's Search for Meaning", ["Frankl, Viktor E."], 1946, ["Psychology", "Holocaust survivors", "Meaning (Psychology)", "Memoir"],
     "A psychiatrist's memoir of the concentration camps and his argument that meaning sustains us through suffering.", "book", "adult", "en", "150.195", "9780807014295"),
    ("The Wealth of Nations", ["Smith, Adam"], 1776, ["Economics", "Wealth", "Free enterprise", "Money"],
     "The founding work of classical economics, on the division of labour, markets and the invisible hand.", "book", "adult", "en", "330.153", "9780553585971"),
    ("Freakonomics", ["Levitt, Steven D.", "Dubner, Stephen J."], 2005, ["Economics -- Sociological aspects", "Incentives", "Money"],
     "An economist applies data to unexpected questions, from sumo wrestling to drug dealing.", "book", "adult", "en", "330", "9780060731335"),
    ("Salt, Fat, Acid, Heat", ["Nosrat, Samin"], 2017, ["Cooking", "Recipes", "Food"],
     "Master four elements of good cooking and you can cook anything, with illustrated lessons and recipes.", "book", "adult", "en", "641.5", "9781476753836"),
    ("Indian Cookery", ["Jaffrey, Madhur"], 1982, ["Cooking, Indian", "Recipes", "India -- Food"],
     "Classic, approachable recipes from across India by the doyenne of Indian home cooking.", "book", "adult", "en", "641.5954", "9780563364566"),
    ("Planet Earth", ["BBC Natural History Unit"], 2006, ["Nature -- Documentary films", "Wildlife", "Ecology"],
     "The landmark documentary series filming wildlife in every habitat on Earth.", "dvd", "adult", "en", "577", None),
    ("Cosmos: A Spacetime Odyssey", ["Tyson, Neil deGrasse"], 2014, ["Astronomy -- Documentary films", "Cosmology", "Space"],
     "Neil deGrasse Tyson continues Carl Sagan's voyage through the universe in this documentary series.", "dvd", "adult", "en", "520", None),
    ("Pather Panchali", ["Ray, Satyajit"], 1955, ["Bengali films", "Villages -- India -- Drama", "Childhood -- Drama"],
     "Satyajit Ray's debut film follows young Apu and his family's struggles in a Bengal village.", "dvd", "adult", "bn", "791.43", None),
    ("National Geographic Kids", ["National Geographic Society"], 2024, ["Children's periodicals", "Nature", "Science"],
     "Monthly magazine of animals, science and fun facts for curious kids.", "serial", "children", "en", "505", None),
    ("The Economist", ["The Economist Newspaper"], 2024, ["Economics -- Periodicals", "World politics -- Periodicals", "Money"],
     "Weekly news and analysis of international politics, business and finance.", "serial", "adult", "en", "330.05", None),
    ("Becoming", ["Obama, Michelle"], 2018, ["Obama, Michelle, 1964-", "Memoir", "Biography"],
     "The former First Lady's memoir of her childhood in Chicago, career and years in the White House.", "audiobook", "adult", "en", "973.932092", "9780525633686"),
    ("Educated", ["Westover, Tara"], 2018, ["Memoir", "Education", "Survivalism -- Idaho"],
     "Raised by survivalists in the Idaho mountains, Westover first set foot in a classroom at seventeen.", "book", "adult", "en", "270.092", "9780399590504"),
    ("Persepolis", ["Satrapi, Marjane"], 2000, ["Graphic novels", "Iran -- History -- Revolution, 1979", "Memoir"],
     "A graphic memoir of growing up in Tehran during the Islamic Revolution and the war with Iraq.", "comic", "young_adult", "en", "955.054092", "9780375714573"),
    ("Watchmen", ["Moore, Alan", "Gibbons, Dave"], 1987, ["Graphic novels", "Superheroes -- Fiction", "Cold War -- Fiction"],
     "In an alternate 1985, retired costumed heroes investigate the murder of one of their own.", "comic", "adult", "en", "741.5973", "9780930289232"),
]

FIRST_NAMES = ["Aarav", "Diya", "Vivaan", "Ananya", "Arjun", "Isha", "Kabir", "Meera", "Rohan", "Saanvi", "Ishaan", "Priya",
               "Aditya", "Kavya", "Nikhil", "Riya", "Sameer", "Tara", "Yash", "Zoya", "Emma", "Liam", "Olivia", "Noah",
               "Sofia", "Lucas", "Amara", "Mateo", "Hana", "Omar", "Leila", "Chen", "Fatima", "Daniel", "Grace", "Samuel"]
LAST_NAMES = ["Sharma", "Verma", "Gupta", "Iyer", "Nair", "Rao", "Singh", "Patel", "Das", "Khan", "Mehta", "Reddy",
              "Bose", "Joshi", "Kapoor", "Menon", "Smith", "Garcia", "Kim", "Okafor", "Silva", "Müller", "Haddad", "Wang"]
