"""baseline schema

Revision ID: 0001_baseline
Revises: (none)
Create Date: 2026-10-07 22:52:59.365446
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '0001_baseline'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_type', sa.Enum('personal_name', 'corporate_name', 'meeting_name', 'uniform_title', 'topical_subject', 'geographic', 'genre_form', name='authoritytype'), nullable=False),
    sa.Column('heading', sa.String(length=500), nullable=False),
    sa.Column('normalized', sa.String(length=500), nullable=False),
    sa.Column('match_key', sa.String(length=500), nullable=True),
    sa.Column('see_also', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('marc_xml', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('authorities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authorities_auth_type'), ['auth_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_authorities_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_authorities_match_key'), ['match_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_authorities_normalized'), ['normalized'], unique=False)
        batch_op.create_index('uq_authority_heading', ['auth_type', 'normalized'], unique=True, sqlite_where=sa.text('deleted_at IS NULL'), postgresql_where=sa.text('deleted_at IS NULL'))

    op.create_table('biblios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('subtitle', sa.String(length=500), nullable=True),
    sa.Column('authors', sa.JSON(), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('issn', sa.String(length=20), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('pub_year', sa.Integer(), nullable=True),
    sa.Column('edition', sa.String(length=80), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('material_type', sa.String(length=32), nullable=False),
    sa.Column('subjects', sa.JSON(), nullable=False),
    sa.Column('series', sa.String(length=255), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('classification', sa.String(length=40), nullable=True),
    sa.Column('audience', sa.String(length=20), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('marc_xml', sa.Text(), nullable=True),
    sa.Column('ai_enriched', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('biblios', schema=None) as batch_op:
        batch_op.create_index('ix_biblios_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_biblios_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_biblios_isbn'), ['isbn'], unique=False)
        batch_op.create_index(batch_op.f('ix_biblios_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_biblios_material_type'), ['material_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_biblios_pub_year'), ['pub_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_biblios_title'), ['title'], unique=False)
        batch_op.create_index('ix_biblios_updated_at', ['updated_at'], unique=False)

    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branches_code'), ['code'], unique=True)

    op.create_table('copycat_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('sru_version', sa.String(length=8), nullable=False),
    sa.Column('record_schema', sa.String(length=64), nullable=False),
    sa.Column('title_index', sa.String(length=40), nullable=False),
    sa.Column('author_index', sa.String(length=40), nullable=False),
    sa.Column('isbn_index', sa.String(length=40), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('section', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('term', sa.String(length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('public_notes', sa.Text(), nullable=True),
    sa.Column('staff_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'section', 'term')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_term'), ['term'], unique=False)

    op.create_table('item_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('holdable', sa.Boolean(), nullable=False),
    sa.Column('replacement_cost', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_types_code'), ['code'], unique=True)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('locked_by', sa.String(length=128), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('schedule', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_claim', ['status', 'run_at', 'priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_type'), ['type'], unique=False)

    op.create_table('label_layouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('page_size', sa.String(length=16), nullable=False),
    sa.Column('page_width', sa.Double(), nullable=False),
    sa.Column('page_height', sa.Double(), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('cols', sa.Integer(), nullable=False),
    sa.Column('margin_top', sa.Double(), nullable=False),
    sa.Column('margin_left', sa.Double(), nullable=False),
    sa.Column('gutter_x', sa.Double(), nullable=False),
    sa.Column('gutter_y', sa.Double(), nullable=False),
    sa.Column('label_width', sa.Double(), nullable=False),
    sa.Column('label_height', sa.Double(), nullable=False),
    sa.Column('padding', sa.Double(), nullable=False),
    sa.Column('font_size', sa.Double(), nullable=False),
    sa.Column('is_preset', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('patron_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('max_loans', sa.Integer(), nullable=False),
    sa.Column('max_holds', sa.Integer(), nullable=False),
    sa.Column('enrollment_months', sa.Integer(), nullable=False),
    sa.Column('block_fine_threshold', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patron_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patron_categories_code'), ['code'], unique=True)

    op.create_table('rate_limit_counters',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('window_start', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key', 'window_start')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('staff_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('discount_pct', sa.Double(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('worker_heartbeats',
    sa.Column('worker_id', sa.String(length=128), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('concurrency', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('jobs_succeeded', sa.Integer(), nullable=False),
    sa.Column('jobs_failed', sa.Integer(), nullable=False),
    sa.Column('current_jobs', sa.JSON(), nullable=False),
    sa.Column('stopping', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_table('authority_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authority_id', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=500), nullable=False),
    sa.Column('normalized', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['authority_id'], ['authorities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('authority_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authority_variants_authority_id'), ['authority_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_authority_variants_normalized'), ['normalized'], unique=False)

    op.create_table('biblio_authorities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biblio_id', sa.Integer(), nullable=False),
    sa.Column('authority_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('heading', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['authority_id'], ['authorities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['biblio_id'], ['biblios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('biblio_id', 'authority_id', 'role')
    )
    with op.batch_alter_table('biblio_authorities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_biblio_authorities_authority_id'), ['authority_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_biblio_authorities_biblio_id'), ['biblio_id'], unique=False)

    op.create_table('biblio_facets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biblio_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=1), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_norm', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['biblio_id'], ['biblios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('biblio_facets', schema=None) as batch_op:
        batch_op.create_index('ix_biblio_facets_biblio', ['biblio_id', 'kind', 'value'], unique=False)
        batch_op.create_index('ix_biblio_facets_lookup', ['kind', 'value_norm', 'biblio_id'], unique=False)

    op.create_table('branch_calendars',
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('closed_weekdays', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('branch_id')
    )
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('allocated', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_closures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=160), nullable=False),
    sa.Column('repeats_yearly', sa.Boolean(), nullable=False),
    sa.Column('open_override', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_closures', schema=None) as batch_op:
        batch_op.create_index('ix_calendar_closures_day', ['branch_id', 'day'], unique=False)

    op.create_table('circulation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('item_type_id', sa.Integer(), nullable=True),
    sa.Column('loan_days', sa.Integer(), nullable=False),
    sa.Column('max_renewals', sa.Integer(), nullable=False),
    sa.Column('fine_per_day', sa.Integer(), nullable=False),
    sa.Column('fine_cap', sa.Integer(), nullable=False),
    sa.Column('grace_days', sa.Integer(), nullable=False),
    sa.Column('hold_pickup_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['patron_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_type_id'], ['item_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'category_id', 'item_type_id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biblio_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=32), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('item_type_id', sa.Integer(), nullable=False),
    sa.Column('call_number', sa.String(length=64), nullable=True),
    sa.Column('shelf_location', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('available', 'on_loan', 'on_hold_shelf', 'in_transit', 'processing', 'lost', 'damaged', 'withdrawn', name='itemstatus'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('acquired_on', sa.Date(), nullable=True),
    sa.Column('times_borrowed', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['biblio_id'], ['biblios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['item_type_id'], ['item_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_barcode'), ['barcode'], unique=True)
        batch_op.create_index(batch_op.f('ix_items_biblio_id'), ['biblio_id'], unique=False)
        batch_op.create_index('ix_items_biblio_status', ['biblio_id', 'status', 'deleted_at', 'branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_status'), ['status'], unique=False)

    op.create_table('patrons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('home_branch_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('patron', 'librarian', 'admin', name='role'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('keep_history', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('registration_status', sa.String(length=16), nullable=True),
    sa.Column('staff_role_id', sa.Integer(), nullable=True),
    sa.Column('failed_logins', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('sessions_revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['patron_categories.id'], ),
    sa.ForeignKeyConstraint(['home_branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['staff_role_id'], ['staff_roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patrons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patrons_card_number'), ['card_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_patrons_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_patrons_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_patrons_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_patrons_registration_status'), ['registration_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_patrons_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_patrons_staff_role_id'), ['staff_role_id'], unique=False)

    op.create_table('schedule_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slot_at', sa.DateTime(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'slot_at', name='uq_schedule_slot')
    )
    op.create_table('sip_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('institution_id', sa.String(length=64), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('delimiter', sa.String(length=1), nullable=False),
    sa.Column('encoding', sa.String(length=16), nullable=False),
    sa.Column('error_detection', sa.Boolean(), nullable=False),
    sa.Column('idle_timeout', sa.Integer(), nullable=False),
    sa.Column('allowed_networks', sa.String(length=500), nullable=True),
    sa.Column('allow_checkout', sa.Boolean(), nullable=False),
    sa.Column('allow_checkin', sa.Boolean(), nullable=False),
    sa.Column('allow_renew', sa.Boolean(), nullable=False),
    sa.Column('allow_patron_info', sa.Boolean(), nullable=False),
    sa.Column('allow_holds', sa.Boolean(), nullable=False),
    sa.Column('allow_fee_paid', sa.Boolean(), nullable=False),
    sa.Column('allow_block_patron', sa.Boolean(), nullable=False),
    sa.Column('require_patron_password', sa.Boolean(), nullable=False),
    sa.Column('checked_in_ok', sa.Boolean(), nullable=False),
    sa.Column('sort_bins', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sip_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sip_accounts_login'), ['login'], unique=True)

    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_ip', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['patrons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['patrons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)

    op.create_table('auth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('jti_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['patrons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_tokens_jti_hash'), ['jti_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_tokens_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('course_instructors',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('patron_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patron_id'], ['patrons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'patron_id')
    )
    op.create_table('course_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biblio_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('item_type_id', sa.Integer(), nullable=True),
    sa.Column('shelf_location', sa.String(length=64), nullable=True),
    sa.Column('swapped', sa.Boolean(), nullable=False),
    sa.Column('original_item_type_id', sa.Integer(), nullable=True),
    sa.Column('original_shelf_location', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['biblio_id'], ['biblios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_type_id'], ['item_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['original_item_type_id'], ['item_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    with op.batch_alter_table('course_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_items_biblio_id'), ['biblio_id'], unique=False)

    op.create_table('holds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biblio_id', sa.Integer(), nullable=False),
    sa.Column('patron_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('pickup_branch_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'ready', 'fulfilled', 'cancelled', 'expired', name='holdstatus'), nullable=False),
    sa.Column('ready_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('requested_item_id', sa.Integer(), nullable=True),
    sa.Column('suspended', sa.Boolean(), nullable=False),
    sa.Column('suspended_until', sa.Date(), nullable=True),
    sa.Column('not_needed_after', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['biblio_id'], ['biblios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patron_id'], ['patrons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pickup_branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['requested_item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holds_patron_id'), ['patron_id'], unique=False)
        batch_op.create_index('ix_holds_queue', ['biblio_id', 'status', 'created_at'], unique=False)

    op.create_table('kiosk_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_hint', sa.String(length=12), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_ip', sa.String(length=64), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['patrons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kiosk_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kiosk_devices_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kiosk_devices_token_hash'), ['token_hash'], unique=True)

    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('patron_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.Column('renewals', sa.Integer(), nullable=False),
    sa.Column('fine_charged', sa.Integer(), nullable=False),
    sa.Column('issued_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['issued_by_id'], ['patrons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['patron_id'], ['patrons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.create_index('ix_loans_due', ['due_at'], unique=False)
        batch_op.create_index('ix_loans_due_open', ['due_at'], unique=False, sqlite_where=sa.text('returned_at IS NULL'), postgresql_where=sa.text('returned_at IS NULL'))
        batch_op.create_index('ix_loans_issued_cover', ['issued_at', 'item_id', 'branch_id'], unique=False)
        batch_op.create_index('ix_loans_item_activity', ['item_id', 'issued_at', 'patron_id'], unique=False)
        batch_op.create_index('ix_loans_patron_activity', ['patron_id', 'issued_at', 'item_id'], unique=False)
        batch_op.create_index('ix_loans_patron_open', ['patron_id', 'returned_at'], unique=False)
        batch_op.create_index('ix_loans_patron_returns', ['patron_id', 'returned_at', 'due_at'], unique=False)
        batch_op.create_index('ix_loans_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('uq_open_loan_per_item', ['item_id'], unique=True, sqlite_where=sa.text('returned_at IS NULL'), postgresql_where=sa.text('returned_at IS NULL'))

    op.create_table('login_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['patrons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_events_at'), ['at'], unique=False)
        batch_op.create_index('ix_login_events_user_at', ['user_id', 'at'], unique=False)

    op.create_table('message_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patron_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['patron_id'], ['patrons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patron_id', 'code')
    )
    with op.batch_alter_table('message_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_preferences_patron_id'), ['patron_id'], unique=False)

    op.create_table('mfa_recovery_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['patrons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mfa_recovery_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mfa_recovery_codes_user_id'), ['user_id'], unique=False)

    op.create_table('mfa_totp',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('secret_enc', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_step', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['patrons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('notice_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['patrons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'channel')
    )
    with op.batch_alter_table('notice_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notice_templates_code'), ['code'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patron_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=True),
    sa.Column('to_address', sa.String(length=160), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patron_id'], ['patrons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_next_attempt_at'), ['next_attempt_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_patron_id'), ['patron_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_status'), ['status'], unique=False)

    op.create_table('patron_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patron_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('decision_note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patron_id'], ['patrons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['patrons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patron_id')
    )
    with op.batch_alter_table('patron_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patron_registrations_status'), ['status'], unique=False)

    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('biblio_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'ordered', 'received', 'cancelled', name='orderstatus'), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['biblio_id'], ['biblios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['patrons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reading_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reading_lists_owner_id'), ['owner_id'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patron_id', sa.Integer(), nullable=False),
    sa.Column('biblio_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['biblio_id'], ['biblios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patron_id'], ['patrons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patron_id', 'biblio_id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_biblio_id'), ['biblio_id'], unique=False)

    op.create_table('serial_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biblio_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('budget_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'cancelled', name='subscriptionstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('first_issue_on', sa.Date(), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('frequency_interval', sa.Integer(), nullable=False),
    sa.Column('skip_weekdays', sa.JSON(), nullable=False),
    sa.Column('numbering_pattern', sa.String(length=160), nullable=False),
    sa.Column('numbering', sa.JSON(), nullable=False),
    sa.Column('grace_days', sa.Integer(), nullable=False),
    sa.Column('create_items', sa.Boolean(), nullable=False),
    sa.Column('item_type_id', sa.Integer(), nullable=True),
    sa.Column('shelf_location', sa.String(length=64), nullable=True),
    sa.Column('call_number', sa.String(length=48), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('vendor_reference', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['biblio_id'], ['biblios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_type_id'], ['item_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('serial_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_serial_subscriptions_biblio_id'), ['biblio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_serial_subscriptions_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_serial_subscriptions_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_serial_subscriptions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_serial_subscriptions_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('sip_patron_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patron_id', sa.Integer(), nullable=False),
    sa.Column('sip_account_id', sa.Integer(), nullable=True),
    sa.Column('card_retained', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('cleared_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patron_id'], ['patrons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sip_account_id'], ['sip_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sip_patron_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sip_patron_blocks_patron_id'), ['patron_id'], unique=False)

    op.create_table('user_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['patrons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'subject')
    )
    with op.batch_alter_table('user_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_identities_user_id'), ['user_id'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sid', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['patrons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_sid'), ['sid'], unique=True)
        batch_op.create_index('ix_user_sessions_user_active', ['user_id', 'revoked_at'], unique=False)

    op.create_table('course_reserves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_item_id', sa.Integer(), nullable=False),
    sa.Column('public_note', sa.String(length=500), nullable=True),
    sa.Column('staff_note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_item_id'], ['course_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'course_item_id')
    )
    with op.batch_alter_table('course_reserves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_reserves_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_reserves_course_item_id'), ['course_item_id'], unique=False)

    op.create_table('kiosk_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('patron_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('activity', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['kiosk_devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patron_id'], ['patrons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kiosk_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kiosk_sessions_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kiosk_sessions_patron_id'), ['patron_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kiosk_sessions_token_hash'), ['token_hash'], unique=True)

    op.create_table('ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patron_id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('overdue', 'lost', 'manual', 'payment', 'waiver', name='ledgerkind'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['patrons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patron_id'], ['patrons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_patron_id'), ['patron_id'], unique=False)

    op.create_table('purchase_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patron_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'ordered', 'rejected', 'withdrawn', name='suggestionstatus'), nullable=False),
    sa.Column('decision_note', sa.String(length=500), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patron_id'], ['patrons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['patrons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_suggestions_patron_id'), ['patron_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_suggestions_status'), ['status'], unique=False)

    op.create_table('reading_list_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('biblio_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['biblio_id'], ['biblios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['list_id'], ['reading_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id', 'biblio_id')
    )
    op.create_table('serial_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('numbers', sa.JSON(), nullable=False),
    sa.Column('enumeration', sa.String(length=160), nullable=False),
    sa.Column('chronology', sa.String(length=64), nullable=True),
    sa.Column('expected_on', sa.Date(), nullable=False),
    sa.Column('received_on', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('expected', 'arrived', 'late', 'missing', 'claimed', 'not_published', name='serialissuestatus'), nullable=False),
    sa.Column('manual', sa.Boolean(), nullable=False),
    sa.Column('claim_count', sa.Integer(), nullable=False),
    sa.Column('last_claimed_at', sa.DateTime(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['serial_subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'sequence')
    )
    with op.batch_alter_table('serial_issues', schema=None) as batch_op:
        batch_op.create_index('ix_serial_issues_status_expected', ['status', 'expected_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_serial_issues_subscription_id'), ['subscription_id'], unique=False)

    op.create_table('serial_routing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('patron_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['patron_id'], ['patrons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['serial_subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'patron_id')
    )
    with op.batch_alter_table('serial_routing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_serial_routing_subscription_id'), ['subscription_id'], unique=False)

    op.create_table('serial_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch', sa.String(length=32), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=False),
    sa.Column('claimed_by_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['claimed_by_id'], ['patrons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issue_id'], ['serial_issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('serial_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_serial_claims_batch'), ['batch'], unique=False)
        batch_op.create_index(batch_op.f('ix_serial_claims_claimed_at'), ['claimed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_serial_claims_issue_id'), ['issue_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('serial_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_serial_claims_issue_id'))
        batch_op.drop_index(batch_op.f('ix_serial_claims_claimed_at'))
        batch_op.drop_index(batch_op.f('ix_serial_claims_batch'))

    op.drop_table('serial_claims')
    with op.batch_alter_table('serial_routing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_serial_routing_subscription_id'))

    op.drop_table('serial_routing')
    with op.batch_alter_table('serial_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_serial_issues_subscription_id'))
        batch_op.drop_index('ix_serial_issues_status_expected')

    op.drop_table('serial_issues')
    op.drop_table('reading_list_entries')
    with op.batch_alter_table('purchase_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_suggestions_status'))
        batch_op.drop_index(batch_op.f('ix_purchase_suggestions_patron_id'))

    op.drop_table('purchase_suggestions')
    with op.batch_alter_table('ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_patron_id'))

    op.drop_table('ledger')
    with op.batch_alter_table('kiosk_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kiosk_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_kiosk_sessions_patron_id'))
        batch_op.drop_index(batch_op.f('ix_kiosk_sessions_device_id'))

    op.drop_table('kiosk_sessions')
    with op.batch_alter_table('course_reserves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_reserves_course_item_id'))
        batch_op.drop_index(batch_op.f('ix_course_reserves_course_id'))

    op.drop_table('course_reserves')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_user_sessions_user_active')
        batch_op.drop_index(batch_op.f('ix_user_sessions_sid'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('user_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_identities_user_id'))

    op.drop_table('user_identities')
    with op.batch_alter_table('sip_patron_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sip_patron_blocks_patron_id'))

    op.drop_table('sip_patron_blocks')
    with op.batch_alter_table('serial_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_serial_subscriptions_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_serial_subscriptions_status'))
        batch_op.drop_index(batch_op.f('ix_serial_subscriptions_end_date'))
        batch_op.drop_index(batch_op.f('ix_serial_subscriptions_branch_id'))
        batch_op.drop_index(batch_op.f('ix_serial_subscriptions_biblio_id'))

    op.drop_table('serial_subscriptions')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_biblio_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('reading_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reading_lists_owner_id'))

    op.drop_table('reading_lists')
    op.drop_table('purchase_orders')
    with op.batch_alter_table('patron_registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patron_registrations_status'))

    op.drop_table('patron_registrations')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_status'))
        batch_op.drop_index(batch_op.f('ix_notifications_patron_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_next_attempt_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_code'))

    op.drop_table('notifications')
    with op.batch_alter_table('notice_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notice_templates_code'))

    op.drop_table('notice_templates')
    op.drop_table('mfa_totp')
    with op.batch_alter_table('mfa_recovery_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mfa_recovery_codes_user_id'))

    op.drop_table('mfa_recovery_codes')
    with op.batch_alter_table('message_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_preferences_patron_id'))

    op.drop_table('message_preferences')
    with op.batch_alter_table('login_events', schema=None) as batch_op:
        batch_op.drop_index('ix_login_events_user_at')
        batch_op.drop_index(batch_op.f('ix_login_events_at'))

    op.drop_table('login_events')
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_index('uq_open_loan_per_item', sqlite_where=sa.text('returned_at IS NULL'), postgresql_where=sa.text('returned_at IS NULL'))
        batch_op.drop_index('ix_loans_updated_at')
        batch_op.drop_index('ix_loans_patron_returns')
        batch_op.drop_index('ix_loans_patron_open')
        batch_op.drop_index('ix_loans_patron_activity')
        batch_op.drop_index('ix_loans_item_activity')
        batch_op.drop_index('ix_loans_issued_cover')
        batch_op.drop_index('ix_loans_due_open', sqlite_where=sa.text('returned_at IS NULL'), postgresql_where=sa.text('returned_at IS NULL'))
        batch_op.drop_index('ix_loans_due')

    op.drop_table('loans')
    with op.batch_alter_table('kiosk_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kiosk_devices_token_hash'))
        batch_op.drop_index(batch_op.f('ix_kiosk_devices_branch_id'))

    op.drop_table('kiosk_devices')
    with op.batch_alter_table('holds', schema=None) as batch_op:
        batch_op.drop_index('ix_holds_queue')
        batch_op.drop_index(batch_op.f('ix_holds_patron_id'))

    op.drop_table('holds')
    with op.batch_alter_table('course_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_items_biblio_id'))

    op.drop_table('course_items')
    op.drop_table('course_instructors')
    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_tokens_purpose'))
        batch_op.drop_index(batch_op.f('ix_auth_tokens_jti_hash'))

    op.drop_table('auth_tokens')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_tokens_token_hash'))

    op.drop_table('api_tokens')
    with op.batch_alter_table('sip_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sip_accounts_login'))

    op.drop_table('sip_accounts')
    op.drop_table('schedule_runs')
    with op.batch_alter_table('patrons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patrons_staff_role_id'))
        batch_op.drop_index(batch_op.f('ix_patrons_role'))
        batch_op.drop_index(batch_op.f('ix_patrons_registration_status'))
        batch_op.drop_index(batch_op.f('ix_patrons_last_name'))
        batch_op.drop_index(batch_op.f('ix_patrons_email'))
        batch_op.drop_index(batch_op.f('ix_patrons_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_patrons_card_number'))

    op.drop_table('patrons')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_status'))
        batch_op.drop_index(batch_op.f('ix_items_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_items_branch_id'))
        batch_op.drop_index('ix_items_biblio_status')
        batch_op.drop_index(batch_op.f('ix_items_biblio_id'))
        batch_op.drop_index(batch_op.f('ix_items_barcode'))

    op.drop_table('items')
    op.drop_table('circulation_rules')
    with op.batch_alter_table('calendar_closures', schema=None) as batch_op:
        batch_op.drop_index('ix_calendar_closures_day')

    op.drop_table('calendar_closures')
    op.drop_table('budgets')
    op.drop_table('branch_calendars')
    with op.batch_alter_table('biblio_facets', schema=None) as batch_op:
        batch_op.drop_index('ix_biblio_facets_lookup')
        batch_op.drop_index('ix_biblio_facets_biblio')

    op.drop_table('biblio_facets')
    with op.batch_alter_table('biblio_authorities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_biblio_authorities_biblio_id'))
        batch_op.drop_index(batch_op.f('ix_biblio_authorities_authority_id'))

    op.drop_table('biblio_authorities')
    with op.batch_alter_table('authority_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authority_variants_normalized'))
        batch_op.drop_index(batch_op.f('ix_authority_variants_authority_id'))

    op.drop_table('authority_variants')
    op.drop_table('worker_heartbeats')
    op.drop_table('vendors')
    op.drop_table('staff_roles')
    op.drop_table('settings')
    op.drop_table('rate_limit_counters')
    with op.batch_alter_table('patron_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patron_categories_code'))

    op.drop_table('patron_categories')
    op.drop_table('label_layouts')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_type'))
        batch_op.drop_index(batch_op.f('ix_jobs_created_at'))
        batch_op.drop_index('ix_jobs_claim')

    op.drop_table('jobs')
    with op.batch_alter_table('item_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_types_code'))

    op.drop_table('item_types')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_term'))
        batch_op.drop_index(batch_op.f('ix_courses_department'))
        batch_op.drop_index(batch_op.f('ix_courses_code'))
        batch_op.drop_index(batch_op.f('ix_courses_active'))

    op.drop_table('courses')
    op.drop_table('copycat_targets')
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branches_code'))

    op.drop_table('branches')
    with op.batch_alter_table('biblios', schema=None) as batch_op:
        batch_op.drop_index('ix_biblios_updated_at')
        batch_op.drop_index(batch_op.f('ix_biblios_title'))
        batch_op.drop_index(batch_op.f('ix_biblios_pub_year'))
        batch_op.drop_index(batch_op.f('ix_biblios_material_type'))
        batch_op.drop_index(batch_op.f('ix_biblios_language'))
        batch_op.drop_index(batch_op.f('ix_biblios_isbn'))
        batch_op.drop_index(batch_op.f('ix_biblios_deleted_at'))
        batch_op.drop_index('ix_biblios_created_at')

    op.drop_table('biblios')
    with op.batch_alter_table('authorities', schema=None) as batch_op:
        batch_op.drop_index('uq_authority_heading', sqlite_where=sa.text('deleted_at IS NULL'), postgresql_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_authorities_normalized'))
        batch_op.drop_index(batch_op.f('ix_authorities_match_key'))
        batch_op.drop_index(batch_op.f('ix_authorities_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_authorities_auth_type'))

    op.drop_table('authorities')
    # ### end Alembic commands ###
